// Generated by scripts/build-park-curriculum.mjs. Do not edit.
export const CALCULATOR_LEVELS = [
  {
    "id": "one-var-stats",
    "procedureId": "one-var-stats",
    "title": "1-Var Stats",
    "topic": "1.7",
    "coverage": [
      {
        "topic": "1.7",
        "dates": {
          "B": "2026-09-22",
          "E": "2026-09-23"
        },
        "worksheet": "u1_lesson7_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      },
      {
        "topic": "1.8",
        "dates": {
          "B": "2026-09-24",
          "E": "2026-09-23"
        },
        "worksheet": "u1_lesson8_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-09-22",
      "E": "2026-09-23"
    },
    "stem": "Find the five-number summary for L1.",
    "values": {
      "data": [
        4,
        6,
        7,
        8,
        10,
        12,
        13,
        14,
        18,
        20
      ]
    },
    "setup": {
      "lists": {
        "L1": [
          4,
          6,
          7,
          8,
          10,
          12,
          13,
          14,
          18,
          20
        ]
      },
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "ENTER",
      "DOWN",
      "DOWN",
      "ENTER",
      "DOWN"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to the CALC tab.",
      "Open the 1-Var Stats wizard.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result.",
      "Read the five-number summary."
    ],
    "computed": {
      "xbar": 11.2,
      "sumX": 112,
      "sumX2": 1498,
      "Sx": 5.202563470700446,
      "sigmaX": 4.935585071701227,
      "n": 10,
      "minX": 4,
      "Q1": 7,
      "Med": 11,
      "Q3": 14,
      "maxX": 20
    },
    "finalView": {
      "lines": [
        "minX = 4",
        "Q1 = 7",
        "Med = 11",
        "Q3 = 14",
        "maxX = 20"
      ],
      "scrollable": true
    }
  },
  {
    "id": "histogram",
    "procedureId": "histogram",
    "title": "Histogram",
    "topic": "1.5",
    "coverage": [
      {
        "topic": "1.5",
        "dates": {
          "B": "2026-09-15",
          "E": "2026-09-16"
        },
        "worksheet": "u1_lesson5_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-09-15",
      "E": "2026-09-16"
    },
    "stem": "Create a histogram of the following test scores to examine the shape of the distribution: 72, 85, 91, 64, 78, 88, 69, 95, 82, 76, 55, 83, 90, 67, 74.",
    "values": {
      "data": [
        72,
        85,
        91,
        64,
        78,
        88,
        69,
        95,
        82,
        76,
        55,
        83,
        90,
        67,
        74
      ]
    },
    "setup": {
      "lists": {
        "L1": [
          72,
          85,
          91,
          64,
          78,
          88,
          69,
          95,
          82,
          76,
          55,
          83,
          90,
          67,
          74
        ]
      },
      "matrices": {}
    },
    "route": [
      "2ND",
      "Y=",
      "ENTER",
      "DOWN",
      "RIGHT",
      "RIGHT",
      "ENTER",
      "DOWN",
      "DOWN",
      "ZOOM",
      "9",
      "TRACE",
      "RIGHT"
    ],
    "hints": [
      "Choose 2ND.",
      "Choose Y=.",
      "Choose ENTER.",
      "Choose DOWN.",
      "Choose the histogram plot type.",
      "Choose the histogram plot type.",
      "Choose ENTER.",
      "Choose DOWN.",
      "Choose DOWN.",
      "Choose ZOOM.",
      "Choose 9.",
      "Choose TRACE.",
      "Choose RIGHT."
    ],
    "computed": null,
    "finalView": {
      "type": "Histogram",
      "title": "Histogram",
      "settings": {
        "On/Off": "On",
        "Type": "Histogram",
        "Xlist": "L1",
        "Freq": "1",
        "Color": "BLUE"
      },
      "points": [
        {
          "x": 55,
          "upper": 65,
          "y": 2
        },
        {
          "x": 65,
          "upper": 75,
          "y": 4
        },
        {
          "x": 75,
          "upper": 85,
          "y": 4
        },
        {
          "x": 85,
          "upper": 95,
          "y": 4
        },
        {
          "x": 95,
          "upper": 105,
          "y": 1
        }
      ],
      "stats": {
        "xbar": 77.93333333333334,
        "sumX": 1169,
        "sumX2": 92879,
        "Sx": 11.259704808783948,
        "sigmaX": 10.877908295664607,
        "n": 15,
        "minX": 55,
        "Q1": 70.5,
        "Med": 78,
        "Q3": 86.5,
        "maxX": 95
      },
      "traceMode": true,
      "tracePosition": 1,
      "traceInfo": {
        "x": 65,
        "upper": 75,
        "y": 4
      }
    }
  },
  {
    "id": "modified-boxplot",
    "procedureId": "modified-boxplot",
    "title": "Modified Boxplot",
    "topic": "1.7",
    "coverage": [
      {
        "topic": "1.7",
        "dates": {
          "B": "2026-09-22",
          "E": "2026-09-23"
        },
        "worksheet": "u1_lesson7_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      },
      {
        "topic": "1.8",
        "dates": {
          "B": "2026-09-24",
          "E": "2026-09-23"
        },
        "worksheet": "u1_lesson8_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-09-22",
      "E": "2026-09-23"
    },
    "stem": "Construct a modified boxplot for the following car fuel efficiencies (mpg): 22, 25, 28, 30, 31, 33, 34, 36, 38, 42, 55. Identify any outliers.",
    "values": {
      "data": [
        22,
        25,
        28,
        30,
        31,
        33,
        34,
        36,
        38,
        42,
        55
      ]
    },
    "setup": {
      "lists": {
        "L1": [
          22,
          25,
          28,
          30,
          31,
          33,
          34,
          36,
          38,
          42,
          55
        ]
      },
      "matrices": {}
    },
    "route": [
      "2ND",
      "Y=",
      "ENTER",
      "DOWN",
      "RIGHT",
      "RIGHT",
      "RIGHT",
      "ENTER",
      "DOWN",
      "DOWN",
      "ZOOM",
      "9",
      "TRACE",
      "RIGHT"
    ],
    "hints": [
      "Choose 2ND.",
      "Choose Y=.",
      "Choose ENTER.",
      "Choose DOWN.",
      "Choose the modified-boxplot plot type.",
      "Choose the modified-boxplot plot type.",
      "Choose the modified-boxplot plot type.",
      "Choose ENTER.",
      "Choose DOWN.",
      "Choose DOWN.",
      "Choose ZOOM.",
      "Choose 9.",
      "Choose TRACE.",
      "Choose RIGHT."
    ],
    "computed": null,
    "finalView": {
      "type": "ModBoxplot",
      "title": "ModBoxplot",
      "settings": {
        "On/Off": "On",
        "Type": "ModBoxplot",
        "Xlist": "L1",
        "Freq": "1",
        "Color": "BLUE"
      },
      "points": [
        {
          "x": 22,
          "y": 0
        },
        {
          "x": 25,
          "y": 0
        },
        {
          "x": 28,
          "y": 0
        },
        {
          "x": 30,
          "y": 0
        },
        {
          "x": 31,
          "y": 0
        },
        {
          "x": 33,
          "y": 0
        },
        {
          "x": 34,
          "y": 0
        },
        {
          "x": 36,
          "y": 0
        },
        {
          "x": 38,
          "y": 0
        },
        {
          "x": 42,
          "y": 0
        },
        {
          "x": 55,
          "y": 0
        }
      ],
      "stats": {
        "xbar": 34,
        "sumX": 374,
        "sumX2": 13528,
        "Sx": 9.011104260855047,
        "sigmaX": 8.591750800516843,
        "n": 11,
        "minX": 22,
        "Q1": 29,
        "Med": 33,
        "Q3": 37,
        "maxX": 55
      },
      "traceMode": true,
      "tracePosition": 1,
      "traceInfo": {
        "x": 25,
        "y": 0
      }
    }
  },
  {
    "id": "normalcdf",
    "procedureId": "normalcdf",
    "title": "normalcdf",
    "topic": "1.10",
    "coverage": [
      {
        "topic": "1.10",
        "dates": {
          "B": "2026-11-12",
          "E": "2026-11-16"
        },
        "worksheet": "u1_lesson10_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-11-12",
      "E": "2026-11-16"
    },
    "stem": "The distribution of daily processing times at a coffee shop is approximately normal with mean 276 seconds and standard deviation 38 seconds. Find the proportion of orders processed in less than 240 seconds.",
    "values": {
      "lower": -1e+99,
      "upper": 240,
      "mu": 276,
      "sigma": 38
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "2ND",
      "VARS",
      "2",
      "(−)",
      "1",
      "2ND",
      ",",
      "9",
      "9",
      "DOWN",
      "2",
      "4",
      "0",
      "DOWN",
      "2",
      "7",
      "6",
      "DOWN",
      "3",
      "8",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Activate the yellow secondary functions.",
      "Open the DISTR menu.",
      "Open the normalcdf wizard.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Move to the next field.",
      "Enter upper = 240.",
      "Enter upper = 240.",
      "Enter upper = 240.",
      "Move to the next field.",
      "Enter μ = 276.",
      "Enter μ = 276.",
      "Enter μ = 276.",
      "Move to the next field.",
      "Enter σ = 38.",
      "Enter σ = 38.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "value": 0.17172553841722032
    },
    "finalView": [
      "0.1717255384"
    ]
  },
  {
    "id": "invnorm",
    "procedureId": "invnorm",
    "title": "invNorm",
    "topic": "1.10",
    "coverage": [
      {
        "topic": "1.10",
        "dates": {
          "B": "2026-11-12",
          "E": "2026-11-16"
        },
        "worksheet": "u1_lesson10_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-11-12",
      "E": "2026-11-16"
    },
    "stem": "The distribution of salmon lengths in a river is approximately normal with mean 25.5 inches and standard deviation 3.5 inches. What length separates the longest 10% of salmon from the rest?",
    "values": {
      "area": 0.9,
      "mu": 25.5,
      "sigma": 3.5,
      "tail": "left"
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "2ND",
      "VARS",
      "3",
      "0",
      ".",
      "9",
      "DOWN",
      "2",
      "5",
      ".",
      "5",
      "DOWN",
      "3",
      ".",
      "5",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Activate the yellow secondary functions.",
      "Open the DISTR menu.",
      "Open the invNorm wizard.",
      "Enter area = 0.9.",
      "Enter area = 0.9.",
      "Enter area = 0.9.",
      "Move to the next field.",
      "Enter μ = 25.5.",
      "Enter μ = 25.5.",
      "Enter μ = 25.5.",
      "Enter μ = 25.5.",
      "Move to the next field.",
      "Enter σ = 3.5.",
      "Enter σ = 3.5.",
      "Enter σ = 3.5.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "value": 29.985430479406965
    },
    "finalView": [
      "29.98543048"
    ]
  },
  {
    "id": "linreg-a-plus-bx",
    "procedureId": "linreg-a-plus-bx",
    "title": "LinReg(a+bx)",
    "topic": "2.8",
    "coverage": [
      {
        "topic": "2.8",
        "dates": {
          "B": "2027-03-09",
          "E": "2027-03-10"
        },
        "worksheet": "u2_lesson8_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-03-09",
      "E": "2027-03-10"
    },
    "stem": "A researcher collected data on study hours (L1) and exam scores (L2) for 10 students. Find the equation of the least-squares regression line and the correlation coefficient. Data in L1: 2, 3, 5, 6, 7, 8, 9, 10, 11, 12. Data in L2: 65, 70, 74, 80, 78, 85, 88, 91, 93, 96.",
    "values": {
      "xList": "L1",
      "yList": "L2",
      "x_values": [
        2,
        3,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12
      ],
      "y_values": [
        65,
        70,
        74,
        80,
        78,
        85,
        88,
        91,
        93,
        96
      ]
    },
    "setup": {
      "lists": {
        "L1": [
          2,
          3,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12
        ],
        "L2": [
          65,
          70,
          74,
          80,
          78,
          85,
          88,
          91,
          93,
          96
        ]
      },
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "8",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to the CALC tab.",
      "Open LinReg(a+bx).",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "a": 59.61138861138862,
      "b": 3.0669330669330663,
      "r": 0.9903431915400018,
      "r2": 0.9807796370296368,
      "residuals": [
        -0.7452547452547549,
        1.1878121878121846,
        -0.9460539460539508,
        1.9870129870129745,
        -3.079920079920086,
        0.8531468531468533,
        0.7862137862137786,
        0.719280719280718,
        -0.34765234765234254,
        -0.4145854145854173
      ],
      "n": 10,
      "Sxx": 100.10000000000002,
      "Syy": 960,
      "Sxy": 307,
      "xbar": 7.3,
      "ybar": 82
    },
    "finalView": {
      "lines": [
        "y = a + bx",
        "a = 59.61138861",
        "b = 3.066933067",
        "r² = 0.980779637",
        "r = 0.9903431915"
      ],
      "scrollable": true
    }
  },
  {
    "id": "scatterplot",
    "procedureId": "scatterplot",
    "title": "Scatterplot",
    "topic": "2.4",
    "coverage": [
      {
        "topic": "2.4",
        "dates": {
          "B": "2027-03-02",
          "E": "2027-03-05"
        },
        "worksheet": "u2_lesson4_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-03-02",
      "E": "2027-03-05"
    },
    "stem": "An ecologist records the number of bird species and the area (acres) of 10 forest fragments. Create a scatterplot with area on the x-axis and species count on the y-axis to explore the relationship.",
    "values": {
      "xList": "L1",
      "yList": "L2",
      "x_values": [
        5,
        8,
        12,
        15,
        18,
        22,
        26,
        30,
        35,
        40
      ],
      "y_values": [
        12,
        14,
        18,
        19,
        22,
        24,
        27,
        29,
        31,
        34
      ]
    },
    "setup": {
      "lists": {
        "L1": [
          5,
          8,
          12,
          15,
          18,
          22,
          26,
          30,
          35,
          40
        ],
        "L2": [
          12,
          14,
          18,
          19,
          22,
          24,
          27,
          29,
          31,
          34
        ]
      },
      "matrices": {}
    },
    "route": [
      "2ND",
      "Y=",
      "ENTER",
      "DOWN",
      "DOWN",
      "DOWN",
      "ZOOM",
      "9",
      "TRACE",
      "RIGHT"
    ],
    "hints": [
      "Choose 2ND.",
      "Choose Y=.",
      "Choose ENTER.",
      "Choose DOWN.",
      "Choose DOWN.",
      "Choose DOWN.",
      "Choose ZOOM.",
      "Choose 9.",
      "Choose TRACE.",
      "Choose RIGHT."
    ],
    "computed": null,
    "finalView": {
      "type": "Scatter",
      "title": "Scatter",
      "settings": {
        "On/Off": "On",
        "Type": "Scatter",
        "Xlist": "L1",
        "Ylist": "L2",
        "Mark": "square",
        "Color": "BLUE"
      },
      "points": [
        {
          "x": 5,
          "y": 12
        },
        {
          "x": 8,
          "y": 14
        },
        {
          "x": 12,
          "y": 18
        },
        {
          "x": 15,
          "y": 19
        },
        {
          "x": 18,
          "y": 22
        },
        {
          "x": 22,
          "y": 24
        },
        {
          "x": 26,
          "y": 27
        },
        {
          "x": 30,
          "y": 29
        },
        {
          "x": 35,
          "y": 31
        },
        {
          "x": 40,
          "y": 34
        }
      ],
      "stats": {
        "xbar": 21.1,
        "sumX": 211,
        "sumX2": 5667,
        "Sx": 11.618471882691324,
        "sigmaX": 11.022250223978768,
        "n": 10,
        "minX": 5,
        "Q1": 12,
        "Med": 20,
        "Q3": 30,
        "maxX": 40
      },
      "traceMode": true,
      "tracePosition": 1,
      "traceInfo": {
        "x": 8,
        "y": 14
      }
    }
  },
  {
    "id": "residual-plot",
    "procedureId": "residual-plot",
    "title": "Residual plot",
    "topic": "2.7",
    "coverage": [
      {
        "topic": "2.7",
        "dates": {
          "B": "2027-03-08",
          "E": "2027-03-08"
        },
        "worksheet": "u2_lesson7_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-03-08",
      "E": "2027-03-08"
    },
    "stem": "After fitting a least-squares regression line to the relationship between study hours and exam scores, create a residual plot to assess whether a linear model is appropriate.",
    "values": {
      "xList": "L1",
      "residList": "RESID",
      "x_values": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ],
      "y_values": [
        62,
        66,
        69,
        72,
        76,
        79,
        81,
        85,
        88,
        90
      ]
    },
    "setup": {
      "lists": {
        "L1": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10
        ],
        "L2": [
          62,
          66,
          69,
          72,
          76,
          79,
          81,
          85,
          88,
          90
        ]
      },
      "matrices": {}
    },
    "route": [
      "2ND",
      "Y=",
      "ENTER",
      "DOWN",
      "DOWN",
      "DOWN",
      "2ND",
      "STAT",
      "7",
      "ZOOM",
      "9",
      "TRACE",
      "RIGHT"
    ],
    "hints": [
      "Choose 2ND.",
      "Choose Y=.",
      "Choose ENTER.",
      "Choose DOWN.",
      "Choose DOWN.",
      "Choose DOWN.",
      "Use RESID as the vertical list.",
      "Use RESID as the vertical list.",
      "Use RESID as the vertical list.",
      "Choose ZOOM.",
      "Choose 9.",
      "Choose TRACE.",
      "Choose RIGHT."
    ],
    "computed": null,
    "finalView": {
      "type": "Scatter",
      "title": "Scatter",
      "settings": {
        "On/Off": "On",
        "Type": "Scatter",
        "Xlist": "L1",
        "Ylist": "RESID",
        "Mark": "square",
        "Color": "BLUE"
      },
      "points": [
        {
          "x": 1,
          "y": -0.7272727272727217
        },
        {
          "x": 2,
          "y": 0.14545454545455083
        },
        {
          "x": 3,
          "y": 0.018181818181822962
        },
        {
          "x": 4,
          "y": -0.10909090909090402
        },
        {
          "x": 5,
          "y": 0.763636363636369
        },
        {
          "x": 6,
          "y": 0.6363636363636402
        },
        {
          "x": 7,
          "y": -0.49090909090908497
        },
        {
          "x": 8,
          "y": 0.3818181818181863
        },
        {
          "x": 9,
          "y": 0.2545454545454575
        },
        {
          "x": 10,
          "y": -0.8727272727272677
        }
      ],
      "stats": {
        "xbar": 5.5,
        "sumX": 55,
        "sumX2": 385,
        "Sx": 3.0276503540974917,
        "sigmaX": 2.8722813232690143,
        "n": 10,
        "minX": 1,
        "Q1": 3,
        "Med": 5.5,
        "Q3": 8,
        "maxX": 10
      },
      "traceMode": true,
      "tracePosition": 1,
      "traceInfo": {
        "x": 2,
        "y": 0.14545454545455083
      }
    }
  },
  {
    "id": "binompdf",
    "procedureId": "binompdf",
    "title": "binompdf",
    "topic": "4.10",
    "coverage": [
      {
        "topic": "4.10",
        "dates": {
          "B": "2026-11-09",
          "E": "2026-11-09"
        },
        "worksheet": "u4_lesson10-12_live.html",
        "sources": [
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-11-09",
      "E": "2026-11-09"
    },
    "stem": "A basketball player makes 75% of her free throws. In tonight's game, she shoots 10 free throws. What is the probability she makes exactly 8?",
    "values": {
      "n": 10,
      "p": 0.75,
      "x": 8
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "2ND",
      "VARS",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "ENTER",
      "1",
      "0",
      "DOWN",
      "0",
      ".",
      "7",
      "5",
      "DOWN",
      "8",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Activate the yellow secondary functions.",
      "Open the DISTR menu.",
      "Scroll until A:binompdf( is highlighted.",
      "Scroll until A:binompdf( is highlighted.",
      "Scroll until A:binompdf( is highlighted.",
      "Scroll until A:binompdf( is highlighted.",
      "Scroll until A:binompdf( is highlighted.",
      "Scroll until A:binompdf( is highlighted.",
      "Scroll until A:binompdf( is highlighted.",
      "Scroll until A:binompdf( is highlighted.",
      "Scroll until A:binompdf( is highlighted.",
      "Scroll until A:binompdf( is highlighted.",
      "Open the binompdf wizard.",
      "Enter trials = 10.",
      "Enter trials = 10.",
      "Move to the next field.",
      "Enter p = 0.75.",
      "Enter p = 0.75.",
      "Enter p = 0.75.",
      "Enter p = 0.75.",
      "Move to the next field.",
      "Enter x = 8.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "value": 0.28156757354736306
    },
    "finalView": [
      "0.2815675735"
    ]
  },
  {
    "id": "binomcdf",
    "procedureId": "binomcdf",
    "title": "binomcdf",
    "topic": "4.10",
    "coverage": [
      {
        "topic": "4.10",
        "dates": {
          "B": "2026-11-09",
          "E": "2026-11-09"
        },
        "worksheet": "u4_lesson10-12_live.html",
        "sources": [
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-11-09",
      "E": "2026-11-09"
    },
    "stem": "A basketball player makes 75% of her free throws. In tonight's game, she shoots 10 free throws. What is the probability she makes at most 6?",
    "values": {
      "n": 10,
      "p": 0.75,
      "x": 6
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "2ND",
      "VARS",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "ENTER",
      "1",
      "0",
      "DOWN",
      "0",
      ".",
      "7",
      "5",
      "DOWN",
      "6",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Activate the yellow secondary functions.",
      "Open the DISTR menu.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Scroll until B:binomcdf( is highlighted.",
      "Open the binomcdf wizard.",
      "Enter trials = 10.",
      "Enter trials = 10.",
      "Move to the next field.",
      "Enter p = 0.75.",
      "Enter p = 0.75.",
      "Enter p = 0.75.",
      "Enter p = 0.75.",
      "Move to the next field.",
      "Enter x = 6.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "value": 0.2241249084472659
    },
    "finalView": [
      "0.2241249084"
    ]
  },
  {
    "id": "geometpdf",
    "procedureId": "geometpdf",
    "title": "geometpdf",
    "topic": "4.12",
    "coverage": [
      {
        "topic": "4.12",
        "dates": {
          "B": null,
          "E": null
        },
        "worksheet": "u4_lesson10-12_live.html",
        "sources": []
      }
    ],
    "dates": {
      "B": null,
      "E": null
    },
    "stem": "A telemarketer has a 12% chance of making a sale on each call. What is the probability that the first sale occurs on exactly the 5th call?",
    "values": {
      "p": 0.12,
      "x": 5
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "2ND",
      "VARS",
      "ALPHA",
      "COS",
      "0",
      ".",
      "1",
      "2",
      "DOWN",
      "5",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Activate the yellow secondary functions.",
      "Open the DISTR menu.",
      "Press [alpha] to activate letter input.",
      "Press [cos] (the F key) to select geometpdf.",
      "Enter p = 0.12.",
      "Enter p = 0.12.",
      "Enter p = 0.12.",
      "Enter p = 0.12.",
      "Move to the next field.",
      "Enter x = 5.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "value": 0.0719634432
    },
    "finalView": [
      "0.0719634432"
    ]
  },
  {
    "id": "geometcdf",
    "procedureId": "geometcdf",
    "title": "geometcdf",
    "topic": "4.12",
    "coverage": [
      {
        "topic": "4.12",
        "dates": {
          "B": null,
          "E": null
        },
        "worksheet": "u4_lesson10-12_live.html",
        "sources": []
      }
    ],
    "dates": {
      "B": null,
      "E": null
    },
    "stem": "A telemarketer has a 12% chance of making a sale on each call. What is the probability that the first sale occurs within the first 8 calls?",
    "values": {
      "p": 0.12,
      "x": 8
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "2ND",
      "VARS",
      "ALPHA",
      "TAN",
      "0",
      ".",
      "1",
      "2",
      "DOWN",
      "8",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Activate the yellow secondary functions.",
      "Open the DISTR menu.",
      "Press [alpha] to activate letter input.",
      "Press [tan] (the G key) to select geometcdf.",
      "Enter p = 0.12.",
      "Enter p = 0.12.",
      "Enter p = 0.12.",
      "Enter p = 0.12.",
      "Move to the next field.",
      "Enter x = 8.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "value": 0.6403654751944704
    },
    "finalView": [
      "0.6403654752"
    ]
  },
  {
    "id": "normalcdf-sampling",
    "procedureId": "normalcdf-sampling",
    "title": "normalcdf for sampling distribution",
    "topic": "5.7",
    "coverage": [
      {
        "topic": "5.7",
        "dates": {
          "B": "2027-01-25",
          "E": "2027-01-27"
        },
        "worksheet": "u5_lesson7_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-01-25",
      "E": "2027-01-27"
    },
    "stem": "The distribution of daily processing times at a coffee shop is approximately normal with mean 276 seconds and standard deviation 38 seconds. In a random sample of 25 orders, what is the probability that the sample mean processing time is less than 260 seconds?",
    "values": {
      "lower": -1e+99,
      "upper": 260,
      "mu": 276,
      "sigma_xbar": 7.6,
      "note": "sigma/sqrt(n) = 38/sqrt(25) = 7.6"
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "2ND",
      "VARS",
      "2",
      "(−)",
      "1",
      "2ND",
      ",",
      "9",
      "9",
      "DOWN",
      "2",
      "6",
      "0",
      "DOWN",
      "2",
      "7",
      "6",
      "DOWN",
      "7",
      ".",
      "6",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Activate the yellow secondary functions.",
      "Open the DISTR menu.",
      "Open the normalcdf wizard.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Enter lower = -1e+99.",
      "Move to the next field.",
      "Enter upper = 260.",
      "Enter upper = 260.",
      "Enter upper = 260.",
      "Move to the next field.",
      "Enter μ = 276.",
      "Enter μ = 276.",
      "Enter μ = 276.",
      "Move to the next field.",
      "Enter σ = 7.6.",
      "Enter σ = 7.6.",
      "Enter σ = 7.6.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "value": 0.017634203613444966
    },
    "finalView": [
      "0.01763420361"
    ]
  },
  {
    "id": "invnorm-sampling",
    "procedureId": "invnorm-sampling",
    "title": "invNorm for sampling distribution",
    "topic": "5.7",
    "coverage": [
      {
        "topic": "5.7",
        "dates": {
          "B": "2027-01-25",
          "E": "2027-01-27"
        },
        "worksheet": "u5_lesson7_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-01-25",
      "E": "2027-01-27"
    },
    "stem": "The mean height of adult women is 64.5 inches with standard deviation 2.5 inches. For random samples of size 49, what sample mean height separates the top 5% of all possible sample means?",
    "values": {
      "area": 0.95,
      "mu": 64.5,
      "sigma_xbar": 0.357,
      "tail": "left",
      "note": "sigma/sqrt(n) = 2.5/sqrt(49) = 0.357"
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "2ND",
      "VARS",
      "3",
      "0",
      ".",
      "9",
      "5",
      "DOWN",
      "6",
      "4",
      ".",
      "5",
      "DOWN",
      "0",
      ".",
      "3",
      "5",
      "7",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Activate the yellow secondary functions.",
      "Open the DISTR menu.",
      "Open the invNorm wizard.",
      "Enter area = 0.95.",
      "Enter area = 0.95.",
      "Enter area = 0.95.",
      "Enter area = 0.95.",
      "Move to the next field.",
      "Enter μ = 64.5.",
      "Enter μ = 64.5.",
      "Enter μ = 64.5.",
      "Enter μ = 64.5.",
      "Move to the next field.",
      "Enter σ = 0.357.",
      "Enter σ = 0.357.",
      "Enter σ = 0.357.",
      "Enter σ = 0.357.",
      "Enter σ = 0.357.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "value": 65.08721274482193
    },
    "finalView": [
      "65.08721274"
    ]
  },
  {
    "id": "one-propztest",
    "procedureId": "one-propztest",
    "title": "1-PropZTest",
    "topic": "6.4",
    "coverage": [
      {
        "topic": "6.4",
        "dates": {
          "B": "2026-12-08",
          "E": "2026-12-11"
        },
        "worksheet": "u6_lesson4_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-12-08",
      "E": "2026-12-11"
    },
    "stem": "A company claims that at least 70% of its customers are satisfied with their service. In a random sample of 200 customers, 126 reported satisfaction. Test the company's claim at the alpha = 0.05 significance level.",
    "values": {
      "p0": 0.7,
      "x": 126,
      "n": 200,
      "direction": "<"
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "5",
      "0",
      ".",
      "7",
      "DOWN",
      "1",
      "2",
      "6",
      "DOWN",
      "2",
      "0",
      "0",
      "DOWN",
      "RIGHT",
      "ENTER",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Open 1-PropZTest.",
      "Enter p0 = 0.7.",
      "Enter p0 = 0.7.",
      "Enter p0 = 0.7.",
      "Move to the next field.",
      "Enter x = 126.",
      "Enter x = 126.",
      "Enter x = 126.",
      "Move to the next field.",
      "Enter n = 200.",
      "Enter n = 200.",
      "Enter n = 200.",
      "Move to the next field.",
      "Choose <p₀.",
      "Confirm <p₀.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "z": -2.160246899469285,
      "p": 0.015376780629707664,
      "pHat": 0.63,
      "n": 200
    },
    "finalView": {
      "lines": [
        "prop < p0",
        "z = -2.160246899",
        "p = 0.01537678063",
        "p̂ = 0.63",
        "n = 200"
      ],
      "scrollable": false
    }
  },
  {
    "id": "one-propzint",
    "procedureId": "one-propzint",
    "title": "1-PropZInt",
    "topic": "6.2",
    "coverage": [
      {
        "topic": "6.2",
        "dates": {
          "B": "2026-12-04",
          "E": "2026-12-07"
        },
        "worksheet": "u6_lesson1-2_live.html",
        "sources": [
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-12-04",
      "E": "2026-12-07"
    },
    "stem": "A random sample of 80 adults was selected, and 22 indicated they would support eliminating the penny from circulation. Construct a 99% confidence interval for the true proportion of adults who support this idea.",
    "values": {
      "x": 22,
      "n": 80,
      "cLevel": 0.99
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "ALPHA",
      "MATH",
      "2",
      "2",
      "DOWN",
      "8",
      "0",
      "DOWN",
      "0",
      ".",
      "9",
      "9",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Press [alpha] to activate letter input.",
      "Press [math] (the A key) to select 1-PropZInt..",
      "Enter x = 22.",
      "Enter x = 22.",
      "Move to the next field.",
      "Enter n = 80.",
      "Enter n = 80.",
      "Move to the next field.",
      "Enter C-Level = 0.99.",
      "Enter C-Level = 0.99.",
      "Enter C-Level = 0.99.",
      "Enter C-Level = 0.99.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "lower": 0.14640992894901486,
      "upper": 0.4035900710509852,
      "pHat": 0.275,
      "n": 80,
      "ME": 0.12859007105098516
    },
    "finalView": {
      "lines": [
        "(0.1464099289, 0.4035900711)",
        "p̂ = 0.275",
        "n = 80"
      ],
      "scrollable": false
    }
  },
  {
    "id": "two-propztest",
    "procedureId": "two-propztest",
    "title": "2-PropZTest",
    "topic": "6.10",
    "coverage": [
      {
        "topic": "6.10",
        "dates": {
          "B": "2027-01-04",
          "E": "2027-01-06"
        },
        "worksheet": "u6_lesson10_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-01-04",
      "E": "2027-01-06"
    },
    "stem": "A researcher wants to know whether a new flu vaccine formulation is more effective than the standard one. In a random sample of 250 adults who received the new vaccine, 30 developed the flu. In an independent random sample of 240 adults who received the standard vaccine, 45 developed the flu. Is there convincing evidence at alpha = 0.05 that the proportion who develop the flu is lower for the new vaccine?",
    "values": {
      "x1": 30,
      "n1": 250,
      "x2": 45,
      "n2": 240,
      "direction": "<"
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "6",
      "3",
      "0",
      "DOWN",
      "2",
      "5",
      "0",
      "DOWN",
      "4",
      "5",
      "DOWN",
      "2",
      "4",
      "0",
      "DOWN",
      "RIGHT",
      "ENTER",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Open 2-PropZTest.",
      "Enter x1 = 30.",
      "Enter x1 = 30.",
      "Move to the next field.",
      "Enter n1 = 250.",
      "Enter n1 = 250.",
      "Enter n1 = 250.",
      "Move to the next field.",
      "Enter x2 = 45.",
      "Enter x2 = 45.",
      "Move to the next field.",
      "Enter n2 = 240.",
      "Enter n2 = 240.",
      "Enter n2 = 240.",
      "Move to the next field.",
      "Choose <p2.",
      "Confirm <p2.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "z": -2.074544513805148,
      "p": 0.01901438456618654,
      "pHat1": 0.12,
      "pHat2": 0.1875,
      "pHatPooled": 0.15306122448979592,
      "n1": 250,
      "n2": 240
    },
    "finalView": {
      "lines": [
        "p1 < p2",
        "z = -2.074544514",
        "p = 0.01901438457",
        "p̂1 = 0.12",
        "p̂2 = 0.1875",
        "p̂ = 0.1530612245",
        "n1 = 250",
        "n2 = 240"
      ],
      "scrollable": true
    }
  },
  {
    "id": "two-propzint",
    "procedureId": "two-propzint",
    "title": "2-PropZInt",
    "topic": "6.8",
    "coverage": [
      {
        "topic": "6.8",
        "dates": {
          "B": "2026-12-21",
          "E": "2026-12-23"
        },
        "worksheet": "u6_lesson8_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-12-21",
      "E": "2026-12-23"
    },
    "stem": "In a random sample of 120 seniors at a large high school, 78 have a driver's license. In an independent random sample of 110 juniors, 55 have a driver's license. Construct a 95% confidence interval for the difference in the proportions of seniors and juniors who have a driver's license.",
    "values": {
      "x1": 78,
      "n1": 120,
      "x2": 55,
      "n2": 110,
      "cLevel": 0.95
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "ALPHA",
      "APPS",
      "7",
      "8",
      "DOWN",
      "1",
      "2",
      "0",
      "DOWN",
      "5",
      "5",
      "DOWN",
      "1",
      "1",
      "0",
      "DOWN",
      "0",
      ".",
      "9",
      "5",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Press [alpha] to activate letter input.",
      "Press [apps] (the B key) to select 2-PropZInt..",
      "Enter x1 = 78.",
      "Enter x1 = 78.",
      "Move to the next field.",
      "Enter n1 = 120.",
      "Enter n1 = 120.",
      "Enter n1 = 120.",
      "Move to the next field.",
      "Enter x2 = 55.",
      "Enter x2 = 55.",
      "Move to the next field.",
      "Enter n2 = 110.",
      "Enter n2 = 110.",
      "Enter n2 = 110.",
      "Move to the next field.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "lower": 0.023456118639536838,
      "upper": 0.2765438813604632,
      "pHat1": 0.65,
      "pHat2": 0.5,
      "n1": 120,
      "n2": 110,
      "ME": 0.12654388136046318
    },
    "finalView": {
      "lines": [
        "(0.02345611864, 0.2765438814)",
        "p̂1 = 0.65",
        "p̂2 = 0.5",
        "n1 = 120",
        "n2 = 110"
      ],
      "scrollable": false
    }
  },
  {
    "id": "t-test-stats",
    "procedureId": "t-test-stats",
    "title": "T-Test (Stats input)",
    "topic": "7.4",
    "coverage": [
      {
        "topic": "7.4",
        "dates": {
          "B": "2027-02-01",
          "E": "2027-02-03"
        },
        "worksheet": "u7_lesson4_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-02-01",
      "E": "2027-02-03"
    },
    "stem": "A cereal manufacturer claims that boxes contain a mean of 500 grams of cereal. A quality inspector takes a random sample of 36 boxes and finds a sample mean of 494 grams with a standard deviation of 18 grams. Is there evidence at alpha = 0.05 that the true mean is less than 500 grams?",
    "values": {
      "mu0": 500,
      "xbar": 494,
      "sx": 18,
      "n": 36,
      "direction": "<"
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "2",
      "RIGHT",
      "ENTER",
      "DOWN",
      "5",
      "0",
      "0",
      "DOWN",
      "4",
      "9",
      "4",
      "DOWN",
      "1",
      "8",
      "DOWN",
      "3",
      "6",
      "DOWN",
      "RIGHT",
      "ENTER",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Open T-Test.",
      "Choose Stats.",
      "Confirm Stats.",
      "Move to the next field.",
      "Enter μ0 = 500.",
      "Enter μ0 = 500.",
      "Enter μ0 = 500.",
      "Move to the next field.",
      "Enter x̄ = 494.",
      "Enter x̄ = 494.",
      "Enter x̄ = 494.",
      "Move to the next field.",
      "Enter Sx = 18.",
      "Enter Sx = 18.",
      "Move to the next field.",
      "Enter n = 36.",
      "Enter n = 36.",
      "Move to the next field.",
      "Choose <.",
      "Confirm <.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "t": -2,
      "p": 0.026653825931598214,
      "df": 35,
      "xbar": 494,
      "Sx": 18,
      "n": 36
    },
    "finalView": {
      "lines": [
        "μ < μ0",
        "t = -2",
        "p = 0.02665382593",
        "x̄ = 494",
        "Sx = 18",
        "n = 36"
      ],
      "scrollable": false
    }
  },
  {
    "id": "t-test-data",
    "procedureId": "t-test-data",
    "title": "T-Test (Data input)",
    "topic": "7.4",
    "coverage": [
      {
        "topic": "7.4",
        "dates": {
          "B": "2027-02-01",
          "E": "2027-02-03"
        },
        "worksheet": "u7_lesson4_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-02-01",
      "E": "2027-02-03"
    },
    "stem": "A teacher claims the mean score on a standardized test for her class is higher than the national average of 72. She records the following scores from her 12 randomly selected students: 68, 74, 79, 71, 85, 77, 82, 73, 80, 76, 88, 69. Test at alpha = 0.05.",
    "values": {
      "mu0": 72,
      "data": [
        68,
        74,
        79,
        71,
        85,
        77,
        82,
        73,
        80,
        76,
        88,
        69
      ],
      "direction": ">"
    },
    "setup": {
      "lists": {
        "L1": [
          68,
          74,
          79,
          71,
          85,
          77,
          82,
          73,
          80,
          76,
          88,
          69
        ]
      },
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "2",
      "DOWN",
      "7",
      "2",
      "DOWN",
      "DOWN",
      "DOWN",
      "RIGHT",
      "RIGHT",
      "ENTER",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Open T-Test with Data input selected.",
      "Move to the next field.",
      "Enter μ0 = 72.",
      "Enter μ0 = 72.",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Choose >.",
      "Choose >.",
      "Confirm >.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "t": 2.678970194559078,
      "p": 0.010723805287087829,
      "df": 11,
      "xbar": 76.83333333333333,
      "Sx": 6.249848483011893,
      "n": 12
    },
    "finalView": {
      "lines": [
        "μ > μ0",
        "t = 2.678970195",
        "p = 0.01072380529",
        "x̄ = 76.83333333",
        "Sx = 6.249848483",
        "n = 12"
      ],
      "scrollable": false
    }
  },
  {
    "id": "t-interval-stats",
    "procedureId": "t-interval-stats",
    "title": "TInterval (Stats input)",
    "topic": "7.2",
    "coverage": [
      {
        "topic": "7.2",
        "dates": {
          "B": "2027-01-28",
          "E": "2027-01-29"
        },
        "worksheet": "u7_lesson2_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-01-28",
      "E": "2027-01-29"
    },
    "stem": "A random sample of 45 students at a university had a mean GPA of 3.12 with a standard deviation of 0.48. Construct a 95% confidence interval for the mean GPA of all students at the university.",
    "values": {
      "xbar": 3.12,
      "sx": 0.48,
      "n": 45,
      "cLevel": 0.95
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "8",
      "RIGHT",
      "ENTER",
      "DOWN",
      "3",
      ".",
      "1",
      "2",
      "DOWN",
      "0",
      ".",
      "4",
      "8",
      "DOWN",
      "4",
      "5",
      "DOWN",
      "0",
      ".",
      "9",
      "5",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Press [8] to open TInterval.",
      "Choose Stats.",
      "Confirm Stats.",
      "Move to the next field.",
      "Enter x̄ = 3.12.",
      "Enter x̄ = 3.12.",
      "Enter x̄ = 3.12.",
      "Enter x̄ = 3.12.",
      "Move to the next field.",
      "Enter Sx = 0.48.",
      "Enter Sx = 0.48.",
      "Enter Sx = 0.48.",
      "Enter Sx = 0.48.",
      "Move to the next field.",
      "Enter n = 45.",
      "Enter n = 45.",
      "Move to the next field.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "lower": 2.9757920353246363,
      "upper": 3.264207964675364,
      "xbar": 3.12,
      "Sx": 0.48,
      "n": 45,
      "df": 44,
      "ME": 0.14420796467536384
    },
    "finalView": {
      "lines": [
        "(2.975792035, 3.264207965)",
        "x̄ = 3.12",
        "Sx = 0.48",
        "n = 45"
      ],
      "scrollable": false
    }
  },
  {
    "id": "t-interval-data",
    "procedureId": "t-interval-data",
    "title": "TInterval (Data input)",
    "topic": "7.2",
    "coverage": [
      {
        "topic": "7.2",
        "dates": {
          "B": "2027-01-28",
          "E": "2027-01-29"
        },
        "worksheet": "u7_lesson2_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-01-28",
      "E": "2027-01-29"
    },
    "stem": "A biologist measures the lengths (in cm) of 10 randomly caught fish from a lake: 22.1, 25.3, 19.8, 23.5, 24.7, 21.0, 26.4, 20.2, 23.9, 22.6. Construct a 90% confidence interval for the true mean length of fish in the lake.",
    "values": {
      "data": [
        22.1,
        25.3,
        19.8,
        23.5,
        24.7,
        21,
        26.4,
        20.2,
        23.9,
        22.6
      ],
      "cLevel": 0.9
    },
    "setup": {
      "lists": {
        "L1": [
          22.1,
          25.3,
          19.8,
          23.5,
          24.7,
          21,
          26.4,
          20.2,
          23.9,
          22.6
        ]
      },
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "8",
      "DOWN",
      "DOWN",
      "DOWN",
      "0",
      ".",
      "9",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Press [8] to open TInterval with Data input selected.",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Enter C-Level = 0.9.",
      "Enter C-Level = 0.9.",
      "Enter C-Level = 0.9.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "lower": 21.67082804552159,
      "upper": 24.22917195447841,
      "xbar": 22.95,
      "Sx": 2.206681772355145,
      "n": 10,
      "df": 9,
      "ME": 1.279171954478409
    },
    "finalView": {
      "lines": [
        "(21.67082805, 24.22917195)",
        "x̄ = 22.95",
        "Sx = 2.206681772",
        "n = 10"
      ],
      "scrollable": false
    }
  },
  {
    "id": "two-samp-ttest",
    "procedureId": "two-samp-ttest",
    "title": "2-SampTTest",
    "topic": "7.8",
    "coverage": [
      {
        "topic": "7.8",
        "dates": {
          "B": "2027-02-11",
          "E": "2027-02-22"
        },
        "worksheet": "u7_lesson8_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-02-11",
      "E": "2027-02-22"
    },
    "stem": "A researcher wants to know whether a new teaching method produces different test scores than the traditional method. A random sample of 28 students using the new method had a mean score of 78.5 (s = 9.2), while 32 students using the traditional method had a mean of 73.1 (s = 10.4). Test at alpha = 0.05.",
    "values": {
      "xbar1": 78.5,
      "sx1": 9.2,
      "n1": 28,
      "xbar2": 73.1,
      "sx2": 10.4,
      "n2": 32,
      "direction": "!="
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "4",
      "RIGHT",
      "DOWN",
      "7",
      "8",
      ".",
      "5",
      "DOWN",
      "9",
      ".",
      "2",
      "DOWN",
      "2",
      "8",
      "DOWN",
      "7",
      "3",
      ".",
      "1",
      "DOWN",
      "1",
      "0",
      ".",
      "4",
      "DOWN",
      "3",
      "2",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Open 2-SampTTest.",
      "Choose Stats.",
      "Move to the next field.",
      "Enter x̄1 = 78.5.",
      "Enter x̄1 = 78.5.",
      "Enter x̄1 = 78.5.",
      "Enter x̄1 = 78.5.",
      "Move to the next field.",
      "Enter Sx1 = 9.2.",
      "Enter Sx1 = 9.2.",
      "Enter Sx1 = 9.2.",
      "Move to the next field.",
      "Enter n1 = 28.",
      "Enter n1 = 28.",
      "Move to the next field.",
      "Enter x̄2 = 73.1.",
      "Enter x̄2 = 73.1.",
      "Enter x̄2 = 73.1.",
      "Enter x̄2 = 73.1.",
      "Move to the next field.",
      "Enter Sx2 = 10.4.",
      "Enter Sx2 = 10.4.",
      "Enter Sx2 = 10.4.",
      "Enter Sx2 = 10.4.",
      "Move to the next field.",
      "Enter n2 = 32.",
      "Enter n2 = 32.",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "t": 2.134061120837426,
      "p": 0.03707790725048565,
      "df": 57.98986778045954,
      "x1": 78.5,
      "x2": 73.1,
      "Sx1": 9.2,
      "Sx2": 10.4,
      "n1": 28,
      "n2": 32,
      "xbar1": 78.5,
      "xbar2": 73.1
    },
    "finalView": {
      "lines": [
        "μ1 ≠ μ2",
        "t = 2.134061121",
        "p = 0.03707790725",
        "df = 57.98986778",
        "x̄1 = 78.5",
        "x̄2 = 73.1",
        "Sx1 = 9.2",
        "Sx2 = 10.4",
        "n1 = 28",
        "n2 = 32"
      ],
      "scrollable": true
    }
  },
  {
    "id": "two-samp-tint",
    "procedureId": "two-samp-tint",
    "title": "2-SampTInt",
    "topic": "7.6",
    "coverage": [
      {
        "topic": "7.6",
        "dates": {
          "B": "2027-02-08",
          "E": "2027-02-10"
        },
        "worksheet": "u7_lesson6_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-02-08",
      "E": "2027-02-10"
    },
    "stem": "A health study compares the mean systolic blood pressure of 40 runners (mean 118, s = 10.5) with 35 non-runners (mean 128, s = 14.3). Construct a 95% confidence interval for the difference in mean blood pressure (runners minus non-runners).",
    "values": {
      "xbar1": 118,
      "sx1": 10.5,
      "n1": 40,
      "xbar2": 128,
      "sx2": 14.3,
      "n2": 35,
      "cLevel": 0.95
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "0",
      "RIGHT",
      "DOWN",
      "1",
      "1",
      "8",
      "DOWN",
      "1",
      "0",
      ".",
      "5",
      "DOWN",
      "4",
      "0",
      "DOWN",
      "1",
      "2",
      "8",
      "DOWN",
      "1",
      "4",
      ".",
      "3",
      "DOWN",
      "3",
      "5",
      "DOWN",
      "0",
      ".",
      "9",
      "5",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Press [0] to open 2-SampTInt.",
      "Choose Stats.",
      "Move to the next field.",
      "Enter x̄1 = 118.",
      "Enter x̄1 = 118.",
      "Enter x̄1 = 118.",
      "Move to the next field.",
      "Enter Sx1 = 10.5.",
      "Enter Sx1 = 10.5.",
      "Enter Sx1 = 10.5.",
      "Enter Sx1 = 10.5.",
      "Move to the next field.",
      "Enter n1 = 40.",
      "Enter n1 = 40.",
      "Move to the next field.",
      "Enter x̄2 = 128.",
      "Enter x̄2 = 128.",
      "Enter x̄2 = 128.",
      "Move to the next field.",
      "Enter Sx2 = 14.3.",
      "Enter Sx2 = 14.3.",
      "Enter Sx2 = 14.3.",
      "Enter Sx2 = 14.3.",
      "Move to the next field.",
      "Enter n2 = 35.",
      "Enter n2 = 35.",
      "Move to the next field.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "lower": -15.862340340525478,
      "upper": -4.137659659474522,
      "df": 61.67904038854814,
      "x1": 118,
      "x2": 128,
      "Sx1": 10.5,
      "Sx2": 14.3,
      "n1": 40,
      "n2": 35,
      "ME": 5.862340340525478,
      "xbar1": 118,
      "xbar2": 128
    },
    "finalView": {
      "lines": [
        "(-15.86234034, -4.137659659)",
        "df = 61.67904039",
        "x̄1 = 118",
        "x̄2 = 128",
        "Sx1 = 10.5",
        "Sx2 = 14.3",
        "n1 = 40",
        "n2 = 35"
      ],
      "scrollable": true
    }
  },
  {
    "id": "matrix-entry",
    "procedureId": "matrix-entry",
    "title": "Enter matrix",
    "topic": "8.5",
    "coverage": [
      {
        "topic": "8.5",
        "dates": {
          "B": "2027-01-12",
          "E": "2027-01-13"
        },
        "worksheet": "u8_lesson5_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-01-12",
      "E": "2027-01-13"
    },
    "stem": "Enter the following two-way table into Matrix [A] on your calculator so you can run a chi-square test. The table has 3 rows and 2 columns: [[30, 70], [80, 60], [110, 50]].",
    "values": {
      "rows": 3,
      "cols": 2,
      "matrix": [
        [
          30,
          70
        ],
        [
          80,
          60
        ],
        [
          110,
          50
        ]
      ]
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "2ND",
      "x⁻¹",
      "RIGHT",
      "RIGHT",
      "ENTER",
      "3",
      "ENTER",
      "2",
      "ENTER",
      "3",
      "0",
      "ENTER",
      "7",
      "0",
      "ENTER",
      "8",
      "0",
      "ENTER",
      "6",
      "0",
      "ENTER",
      "1",
      "1",
      "0",
      "ENTER",
      "5",
      "0",
      "ENTER"
    ],
    "hints": [
      "Choose 2ND.",
      "Choose x⁻¹.",
      "Choose RIGHT.",
      "Choose RIGHT.",
      "Choose ENTER.",
      "Enter rows = 3.",
      "Choose ENTER.",
      "Enter columns = 2.",
      "Choose ENTER.",
      "Enter cell 1 = 30.",
      "Enter cell 1 = 30.",
      "Choose ENTER.",
      "Enter cell 2 = 70.",
      "Enter cell 2 = 70.",
      "Choose ENTER.",
      "Enter cell 3 = 80.",
      "Enter cell 3 = 80.",
      "Choose ENTER.",
      "Enter cell 4 = 60.",
      "Enter cell 4 = 60.",
      "Choose ENTER.",
      "Enter cell 5 = 110.",
      "Enter cell 5 = 110.",
      "Enter cell 5 = 110.",
      "Choose ENTER.",
      "Enter cell 6 = 50.",
      "Enter cell 6 = 50.",
      "Choose ENTER."
    ],
    "computed": null,
    "finalView": {
      "name": "[A]",
      "dimensions": [
        3,
        2
      ],
      "dimension": null,
      "columns": [
        "C1",
        "C2"
      ],
      "rows": [
        [
          30,
          70
        ],
        [
          80,
          60
        ],
        [
          110,
          50
        ]
      ],
      "cursorRow": 0,
      "cursorCol": 0,
      "entry": null
    }
  },
  {
    "id": "chi-square-gof-test",
    "procedureId": "chi-square-gof-test",
    "title": "χ²GOF-Test",
    "topic": "8.2",
    "coverage": [
      {
        "topic": "8.2",
        "dates": {
          "B": null,
          "E": null
        },
        "worksheet": "u8_lesson2_live.html",
        "sources": []
      }
    ],
    "dates": {
      "B": null,
      "E": null
    },
    "stem": "A candy company claims its bags contain 30% red, 25% blue, 20% green, 15% yellow, and 10% orange candies. A random sample of 200 candies from a bag yields: 72 red, 46 blue, 38 green, 24 yellow, and 20 orange. At alpha = 0.05, test whether the distribution matches the company's claim.",
    "values": {
      "observed": [
        72,
        46,
        38,
        24,
        20
      ],
      "expected_proportions": [
        0.3,
        0.25,
        0.2,
        0.15,
        0.1
      ],
      "n": 200,
      "df": 4
    },
    "setup": {
      "lists": {
        "L1": [
          72,
          46,
          38,
          24,
          20
        ],
        "L2": [
          60,
          50,
          40,
          30,
          20
        ]
      },
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "ALPHA",
      "x⁻¹",
      "DOWN",
      "DOWN",
      "4",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Press [alpha] to activate letter input.",
      "Press [x⁻¹] (the D key) to select χ²GOF-Test..",
      "Move to the next field.",
      "Move to the next field.",
      "Enter df = 4.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "chi2": 4.02,
      "p": 0.4033059107531032,
      "df": 4
    },
    "finalView": {
      "lines": [
        "χ² = 4.02",
        "p = 0.4033059108",
        "df = 4"
      ],
      "scrollable": false
    }
  },
  {
    "id": "chi-square-test",
    "procedureId": "chi-square-test",
    "title": "χ²-Test",
    "topic": "8.5",
    "coverage": [
      {
        "topic": "8.5",
        "dates": {
          "B": "2027-01-12",
          "E": "2027-01-13"
        },
        "worksheet": "u8_lesson5_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2027-01-12",
      "E": "2027-01-13"
    },
    "stem": "A survey asked 400 randomly selected adults about their exercise habits (none, moderate, intense) and their stress level (low, high). The results are summarized in a 2x3 table. At alpha = 0.05, test whether stress level is associated with exercise frequency. Observed counts: None/Low: 30, None/High: 70, Moderate/Low: 80, Moderate/High: 60, Intense/Low: 110, Intense/High: 50.",
    "values": {
      "matrix": [
        [
          30,
          70
        ],
        [
          80,
          60
        ],
        [
          110,
          50
        ]
      ],
      "rows": 3,
      "cols": 2,
      "df": 2
    },
    "setup": {
      "lists": {},
      "matrices": {
        "[A]": [
          [
            30,
            70
          ],
          [
            80,
            60
          ],
          [
            110,
            50
          ]
        ]
      }
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "ALPHA",
      "PRGM",
      "DOWN",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Press [alpha] to activate letter input.",
      "Press [prgm] (the C key) to select χ²-Test..",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "chi2": 37.734487734487736,
      "p": 6.398233720616986e-9,
      "df": 2,
      "expected": [
        [
          55,
          45
        ],
        [
          77,
          63
        ],
        [
          88,
          72
        ]
      ]
    },
    "finalView": {
      "lines": [
        "χ² = 37.73448773",
        "p = 6.398233721E-9",
        "df = 2"
      ],
      "scrollable": false
    }
  },
  {
    "id": "linreg-ttest",
    "procedureId": "linreg-ttest",
    "title": "LinRegTTest",
    "topic": "9.5",
    "coverage": [
      {
        "topic": "9.5",
        "dates": {
          "B": null,
          "E": null
        },
        "worksheet": "u9_lesson5_live.html",
        "sources": []
      }
    ],
    "dates": {
      "B": null,
      "E": null
    },
    "stem": "A wildlife biologist measured the age (months) and weight (pounds) of 15 randomly selected adolescent moose. After verifying conditions, the computer output shows slope b = 2.34, SE_b = 0.48, and the data are stored in L1 and L2. At alpha = 0.05, is there convincing evidence of a linear relationship between age and weight?",
    "values": {
      "beta0": 0,
      "xList": "L1",
      "yList": "L2",
      "x_values": [
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20
      ],
      "y_values": [
        71.2,
        60.5,
        57.4,
        59.1,
        78.1,
        79.4,
        76.4,
        81.7,
        71.7,
        73.7,
        94.8,
        78.8,
        83,
        100.6,
        96.8
      ],
      "direction": "!="
    },
    "setup": {
      "lists": {
        "L1": [
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20
        ],
        "L2": [
          71.2,
          60.5,
          57.4,
          59.1,
          78.1,
          79.4,
          76.4,
          81.7,
          71.7,
          73.7,
          94.8,
          78.8,
          83,
          100.6,
          96.8
        ]
      },
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "ALPHA",
      "COS",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Press [alpha] to activate letter input.",
      "Press [cos] (the F key) to select LinRegTTest..",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "t": 4.968011732958265,
      "p": 0.0002570980154870117,
      "df": 13,
      "a": 46.875952380952185,
      "b": 2.3592857142857286,
      "s": 7.946519269351111,
      "r2": 0.654999827491677,
      "r": 0.8093205962359273
    },
    "finalView": {
      "lines": [
        "β and ρ ≠ 0",
        "t = 4.968011733",
        "p = 2.570980155E-4",
        "df = 13",
        "a = 46.87595238",
        "b = 2.359285714",
        "s = 7.946519269",
        "r² = 0.6549998275",
        "r = 0.8093205962"
      ],
      "scrollable": true
    }
  },
  {
    "id": "linreg-tint",
    "procedureId": "linreg-tint",
    "title": "LinRegTInt",
    "topic": "9.2",
    "coverage": [
      {
        "topic": "9.2",
        "dates": {
          "B": null,
          "E": null
        },
        "worksheet": "u9_lesson2_live.html",
        "sources": []
      }
    ],
    "dates": {
      "B": null,
      "E": null
    },
    "stem": "A researcher collected height (cm) and foot length (cm) data for 25 randomly selected adults. The data are in L1 (foot length) and L2 (height). Construct a 95% confidence interval for the true slope of the regression of height on foot length.",
    "values": {
      "xList": "L1",
      "yList": "L2",
      "x_values": [
        22.1,
        22.4,
        22.8,
        23,
        23.4,
        23.7,
        24.1,
        24.3,
        24.8,
        25,
        25.4,
        25.7,
        26.1,
        26.4,
        26.8,
        27,
        27.3,
        27.7,
        28,
        28.4,
        28.7,
        29,
        29.4,
        29.7,
        30.1
      ],
      "y_values": [
        158,
        160,
        161,
        162,
        164,
        165,
        167,
        168,
        170,
        171,
        172,
        174,
        175,
        177,
        178,
        180,
        181,
        183,
        184,
        186,
        187,
        189,
        190,
        192,
        193
      ],
      "cLevel": 0.95
    },
    "setup": {
      "lists": {
        "L1": [
          22.1,
          22.4,
          22.8,
          23,
          23.4,
          23.7,
          24.1,
          24.3,
          24.8,
          25,
          25.4,
          25.7,
          26.1,
          26.4,
          26.8,
          27,
          27.3,
          27.7,
          28,
          28.4,
          28.7,
          29,
          29.4,
          29.7,
          30.1
        ],
        "L2": [
          158,
          160,
          161,
          162,
          164,
          165,
          167,
          168,
          170,
          171,
          172,
          174,
          175,
          177,
          178,
          180,
          181,
          183,
          184,
          186,
          187,
          189,
          190,
          192,
          193
        ]
      },
      "matrices": {}
    },
    "route": [
      "STAT",
      "RIGHT",
      "RIGHT",
      "ALPHA",
      "TAN",
      "DOWN",
      "DOWN",
      "DOWN",
      "0",
      ".",
      "9",
      "5",
      "DOWN",
      "DOWN",
      "ENTER"
    ],
    "hints": [
      "Press [STAT] to open the statistics menu.",
      "Move to CALC.",
      "Move to TESTS.",
      "Press [alpha] to activate letter input.",
      "Press [tan] (the G key) to select LinRegTInt..",
      "Move to the next field.",
      "Move to the next field.",
      "Move to the next field.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Enter C-Level = 0.95.",
      "Move to the next field.",
      "Move to the next field.",
      "Calculate the result."
    ],
    "computed": {
      "lower": 4.33839815058364,
      "upper": 4.460672775084901,
      "b": 4.399535462834271,
      "df": 23,
      "s": 0.35376441930399155,
      "r2": 0.9989631901130949,
      "r": 0.9994814606150005
    },
    "finalView": {
      "lines": [
        "(4.338398151, 4.460672775)",
        "df = 23",
        "a = {a}",
        "b = 4.399535463",
        "s = 0.3537644193",
        "r² = 0.9989631901",
        "r = 0.9994814606"
      ],
      "scrollable": true
    }
  },
  {
    "id": "randint-sampling",
    "procedureId": "randint-sampling",
    "title": "randIntNoRep (random sample)",
    "topic": "3.3",
    "coverage": [
      {
        "topic": "3.3",
        "dates": {
          "B": "2026-10-01",
          "E": "2026-09-30"
        },
        "worksheet": "u3_lesson3_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-10-01",
      "E": "2026-09-30"
    },
    "stem": "A counselor wants to interview a simple random sample of 5 of the 30 students in a class. Number the students 1 through 30. Seed your calculator with 42, then use randIntNoRep to select which students are interviewed.",
    "values": {
      "seed": 42,
      "lo": 1,
      "hi": 30,
      "n": 5
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "4",
      "2",
      "STO→",
      "MATH",
      "RIGHT",
      "RIGHT",
      "RIGHT",
      "1",
      "ENTER",
      "MATH",
      "RIGHT",
      "RIGHT",
      "RIGHT",
      "8",
      "1",
      "DOWN",
      "3",
      "0",
      "DOWN",
      "5",
      "DOWN",
      "ENTER",
      "ENTER"
    ],
    "hints": [
      "Enter seed = 42.",
      "Enter seed = 42.",
      "Choose STO→.",
      "Choose MATH.",
      "Choose RIGHT.",
      "Choose RIGHT.",
      "Choose RIGHT.",
      "Choose 1.",
      "Choose ENTER.",
      "Choose MATH.",
      "Choose RIGHT.",
      "Choose RIGHT.",
      "Choose RIGHT.",
      "Choose 8.",
      "Enter lower = 1.",
      "Move to the next field.",
      "Enter upper = 30.",
      "Enter upper = 30.",
      "Move to the next field.",
      "Enter n = 5.",
      "Move to the next field.",
      "Calculate the result.",
      "Evaluate the random draw."
    ],
    "computed": null,
    "finalView": [
      "42→rand",
      "42",
      "randIntNoRep(1,30,5)",
      "{27 11 2 3 8}"
    ]
  },
  {
    "id": "randint-assignment",
    "procedureId": "randint-assignment",
    "title": "randIntNoRep (random assignment)",
    "topic": "3.6",
    "coverage": [
      {
        "topic": "3.6",
        "dates": {
          "B": "2026-10-06",
          "E": "2026-10-07"
        },
        "worksheet": "u3_lesson6-7_live.html",
        "sources": [
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-10-06",
      "E": "2026-10-07"
    },
    "stem": "Twelve volunteers, numbered 1 through 12, will be split evenly between Treatment A and Treatment B. Seed your calculator with 8, generate a random ordering of 1-12 with randIntNoRep, and assign the FIRST 6 numbers to Treatment A.",
    "values": {
      "seed": 8,
      "lo": 1,
      "hi": 12,
      "n": 12,
      "groupSize": 6
    },
    "setup": {
      "lists": {},
      "matrices": {}
    },
    "route": [
      "8",
      "STO→",
      "MATH",
      "RIGHT",
      "RIGHT",
      "RIGHT",
      "1",
      "ENTER",
      "MATH",
      "RIGHT",
      "RIGHT",
      "RIGHT",
      "8",
      "1",
      "DOWN",
      "1",
      "2",
      "DOWN",
      "1",
      "2",
      "DOWN",
      "ENTER",
      "ENTER"
    ],
    "hints": [
      "Enter seed = 8.",
      "Choose STO→.",
      "Choose MATH.",
      "Choose RIGHT.",
      "Choose RIGHT.",
      "Choose RIGHT.",
      "Choose 1.",
      "Choose ENTER.",
      "Choose MATH.",
      "Choose RIGHT.",
      "Choose RIGHT.",
      "Choose RIGHT.",
      "Choose 8.",
      "Enter lower = 1.",
      "Move to the next field.",
      "Enter upper = 12.",
      "Enter upper = 12.",
      "Move to the next field.",
      "Enter n = 12.",
      "Enter n = 12.",
      "Move to the next field.",
      "Calculate the result.",
      "Evaluate the random draw."
    ],
    "computed": null,
    "finalView": [
      "8→rand",
      "8",
      "randIntNoRep(1,12,12)",
      "{9 10 4 5 6 3 8 7 12 2 1 11}"
    ]
  },
  {
    "id": "dotplot",
    "procedureId": "histogram",
    "challenge": "dotplot",
    "title": "Histogram to dot plot",
    "topic": "1.5",
    "coverage": [
      {
        "topic": "1.5",
        "dates": {
          "B": "2026-09-15",
          "E": "2026-09-16"
        },
        "worksheet": "u1_lesson5_live.html",
        "sources": [
          "worksheet",
          "quiz"
        ]
      }
    ],
    "dates": {
      "B": "2026-09-15",
      "E": "2026-09-16"
    },
    "stem": "Create a histogram of the following test scores to examine the shape of the distribution: 72, 85, 91, 64, 78, 88, 69, 95, 82, 76, 55, 83, 90, 67, 74.",
    "values": {
      "data": [
        1,
        1,
        2,
        2,
        2,
        3,
        4,
        4,
        5,
        5
      ]
    },
    "setup": {
      "lists": {
        "L1": [
          1,
          1,
          2,
          2,
          2,
          3,
          4,
          4,
          5,
          5
        ]
      },
      "matrices": {}
    },
    "route": [
      "2ND",
      "Y=",
      "ENTER",
      "DOWN",
      "RIGHT",
      "RIGHT",
      "ENTER",
      "DOWN",
      "DOWN",
      "ZOOM",
      "9",
      "TRACE",
      "RIGHT"
    ],
    "hints": [
      "Choose 2ND.",
      "Choose Y=.",
      "Choose ENTER.",
      "Choose DOWN.",
      "Choose the histogram plot type.",
      "Choose the histogram plot type.",
      "Choose ENTER.",
      "Choose DOWN.",
      "Choose DOWN.",
      "Choose ZOOM.",
      "Choose 9.",
      "Choose TRACE.",
      "Choose RIGHT."
    ],
    "computed": null,
    "finalView": {
      "type": "Histogram",
      "title": "Histogram",
      "settings": {
        "On/Off": "On",
        "Type": "Histogram",
        "Xlist": "L1",
        "Freq": "1",
        "Color": "BLUE"
      },
      "points": [
        {
          "x": 1,
          "upper": 2,
          "y": 2
        },
        {
          "x": 2,
          "upper": 3,
          "y": 3
        },
        {
          "x": 3,
          "upper": 4,
          "y": 1
        },
        {
          "x": 4,
          "upper": 5,
          "y": 2
        },
        {
          "x": 5,
          "upper": 6,
          "y": 2
        }
      ],
      "stats": {
        "xbar": 2.9,
        "sumX": 29,
        "sumX2": 105,
        "Sx": 1.5238839267549948,
        "sigmaX": 1.445683229480096,
        "n": 10,
        "minX": 1,
        "Q1": 2,
        "Med": 2.5,
        "Q3": 4,
        "maxX": 5
      },
      "traceMode": true,
      "tracePosition": 1,
      "traceInfo": {
        "x": 2,
        "upper": 3,
        "y": 3
      }
    }
  }
];
